# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='user_name',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
